location / {
  root /var/www/cicd-learning-journal/current;
  index index.html;
  try_files $uri $uri/ /index.html;
}

location /assets/ {
  root /var/www/cicd-learning-journal/current;
  try_files $uri =404;
  expires 1y;
  add_header Cache-Control "public, immutable";
}
