export const flows = {
  artifact: { id: 'artifact', label: 'Artifact → EC2', subtitle: 'Luồng đang chạy thật trong lab này', package: 'frontend-dist-<commit SHA>', mentalModel: 'CODE → BUILD → STORE → DOWNLOAD → SERVE', nodes: [
    { id: 'repo', kind: 'object', icon: '⌘', title: 'Git repository', kicker: 'SOURCE CODE', short: 'React source + workflow YAML', why: 'Git là nguồn lịch sử và kích hoạt pipeline, không phải thứ được copy lên production.', input: 'Commit trên main', output: 'Source code cho CI runner', owner: 'Developer / GitHub', alternatives: 'GitLab, Azure Repos', remember: 'Production nhận package đã build, không nhận source trực tiếp.' },
    { id: 'ci', kind: 'action', icon: '⚙', title: 'CI runner', kicker: 'ACTION EXECUTOR', short: 'GitHub-hosted Ubuntu', why: 'Runner là máy/process chạy job. Nó checkout, test và build thay cho bạn.', input: 'Source code + package-lock.json', output: 'Kết quả test và dist/', owner: 'GitHub Actions runner', alternatives: 'GitLab Runner, Jenkins agent', remember: 'Runner thực hiện action; nó không phải artifact.' },
    { id: 'build', kind: 'action', icon: '✓', title: 'Test & build', kicker: 'ACTION', short: 'lint · test · Vite build', why: 'CI dừng tại đây nếu code không đáng tin để phát hành. Thất bại không ảnh hưởng website đang chạy.', input: 'Source code', output: 'dist/: HTML, CSS, JS tối ưu', owner: 'CI runner', alternatives: 'Maven package, dotnet publish', remember: 'Build là action. dist/ là output/object.' },
    { id: 'artifact', kind: 'object', icon: '▣', title: 'Build artifact', kicker: 'IMMUTABLE OBJECT', short: 'frontend-dist-a312809', why: 'Artifact là package đã build, được giữ nguyên để deploy đúng bản đã kiểm tra.', input: 'dist/', output: 'ZIP artifact có version theo commit', owner: 'GitHub Actions Artifact Storage', alternatives: '.jar, .zip, binary', remember: 'Build once; deploy đúng artifact đó, không build lại trên EC2.' },
    { id: 'runner', kind: 'action', icon: '↧', title: 'EC2 runner download', kicker: 'CD ACTION', short: 'Self-hosted runner trên EC2', why: 'EC2 chủ động kết nối ra GitHub và tải artifact về. Không cần mở SSH inbound.', input: 'Artifact theo đúng workflow run', output: 'File trong release directory', owner: 'Self-hosted GitHub runner', alternatives: 'AWS SSM, SSH deploy, CodeDeploy agent', remember: 'Runner tải artifact; GitHub không đẩy source thẳng vào EC2.' },
    { id: 'nginx', kind: 'object', icon: '◫', title: 'Nginx + release', kicker: 'RUNTIME', short: 'current → releases/<SHA>', why: 'Nginx phục vụ static files. Symlink current đổi sang release mới giúp rollback nhanh.', input: 'Artifact đã download', output: 'Website cho người dùng', owner: 'EC2 + Nginx', alternatives: 'S3 + CloudFront, Netlify, Vercel', remember: 'Rollback là đổi current về package cũ, không phải git pull.' },
    { id: 'user', kind: 'object', icon: '◉', title: 'User browser', kicker: 'CONSUMER', short: 'HTTP request → HTML/CSS/JS', why: 'Người dùng chỉ nhận response từ Nginx; họ không thấy GitHub, runner hay artifact.', input: 'HTTP request', output: 'Giao diện React trong browser', owner: 'End user', alternatives: 'Mobile app, another service', remember: 'Pipeline kết thúc khi bản mới phục vụ traffic.' },
  ], edges: ['source code', 'run checks', 'dist/ → artifact', 'download artifact', 'serve files', 'HTTP response'] },
  docker: { id: 'docker', label: 'Docker image → Registry', subtitle: 'Luồng tương đương khi runtime cần container', package: 'my-app:a312809', mentalModel: 'CODE → PACKAGE → STORE → PULL → RUN', nodes: [
    { id: 'repo', kind: 'object', icon: '⌘', title: 'Git repository', kicker: 'SOURCE CODE', short: 'App source + Dockerfile', why: 'Dockerfile mô tả cách đóng gói, còn repository vẫn là source of truth.', input: 'Commit', output: 'Source + Dockerfile', owner: 'Developer', alternatives: 'GitLab, Bitbucket', remember: 'Dockerfile không phải Docker image.' },
    { id: 'ci', kind: 'action', icon: '⚙', title: 'CI runner', kicker: 'ACTION EXECUTOR', short: 'checkout · test · build', why: 'Runner kiểm tra code trước khi đóng gói image.', input: 'Source code', output: 'Build context', owner: 'CI runner', alternatives: 'Jenkins agent', remember: 'Runner thực hiện docker build.' },
    { id: 'docker-build', kind: 'action', icon: '⬡', title: 'docker build', kicker: 'ACTION', short: 'Đóng gói app + runtime', why: 'Lệnh này dùng Dockerfile để tạo một package runtime nhất quán.', input: 'Source, Dockerfile, dependencies', output: 'Docker image', owner: 'CI runner', alternatives: 'Buildpacks, Kaniko', remember: 'docker build là action; image là output.' },
    { id: 'image', kind: 'object', icon: '▣', title: 'Docker image', kicker: 'IMMUTABLE OBJECT', short: 'my-app:a312809', why: 'Image chứa app và runtime/dependencies để tạo container giống nhau ở mọi môi trường.', input: 'Output docker build', output: 'Versioned image layers', owner: 'CI runner trước khi push', alternatives: 'OCI image', remember: 'Tag SHA/digest truy vết image về code.' },
    { id: 'registry', kind: 'object', icon: '⇪', title: 'Container registry', kicker: 'IMAGE STORAGE', short: 'ECR · Docker Hub · GHCR', why: 'Registry là ranh giới phân phối giữa nơi build và nơi chạy image.', input: 'docker push image', output: 'Image để runtime pull', owner: 'ECR/Docker Hub/GHCR', alternatives: 'AWS ECR, ACR, Harbor', remember: 'Registry ≈ kho artifact dành riêng cho container image.' },
    { id: 'pull', kind: 'action', icon: '↧', title: 'docker pull', kicker: 'CD ACTION', short: 'Host/orchestrator tải image', why: 'Deployment host lấy đúng image version từ registry; source code không đi sang host.', input: 'Image tag hoặc digest', output: 'Image local trên host', owner: 'EC2, ECS, Kubernetes node', alternatives: 'ECS agent, kubelet', remember: 'Ai pull? Runtime/deployment target, không phải user.' },
    { id: 'container', kind: 'object', icon: '◉', title: 'Running container', kicker: 'RUNTIME OBJECT', short: 'docker run / orchestrator', why: 'Container là instance đang chạy được tạo từ image.', input: 'Image + env vars', output: 'Network service', owner: 'Docker / orchestrator', alternatives: 'ECS task, Kubernetes Pod', remember: 'Image là blueprint; container là instance đang chạy.' },
  ], edges: ['source code', 'test/build', 'build image', 'push image', 'pull exact version', 'run container'] },
};
export const failureCases = [
  { id: 'test', title: 'Test failed', stop: 'CI runner', result: 'Không có artifact/image được tạo.', production: 'Production không thay đổi.', color: 'red' },
  { id: 'store', title: 'Upload / push failed', stop: 'Artifact storage hoặc registry', result: 'Package có thể đã build nhưng CD không lấy được.', production: 'Production không thay đổi.', color: 'amber' },
  { id: 'deploy', title: 'Deploy failed', stop: 'EC2 runner / deployment target', result: 'Bản mới không được kích hoạt.', production: 'Release current cũ vẫn phục vụ.', color: 'amber' },
  { id: 'health', title: 'Health check failed', stop: 'Sau khi runtime khởi động', result: 'Pipeline cần rollback hoặc chặn chuyển traffic.', production: 'Tuỳ strategy: giữ bản cũ hoặc rollback.', color: 'red' },
];
